language: python

python:
  - "3.6"

install:
  - pip install flake8 jupyterlab

script:
  - flake8 .
  - python setup.py sdist
  - python -mpip install dist/*.tar.gz
  - jlpm
  - jupyter labextension install

deploy:
  provider: pypi
  user: __token__
  # password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
